name = "student-management"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
DATA_SOURCE = "supabase"
NEXT_PUBLIC_APP_ENV = "production"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
